### ISSUE TITLE
Specify username in the link in the contribution section of readme

### ISSUE THREAD

**Issue by ivan-kolmychek** [olegantonyan/super_awesome_print#2]
In the [Contributing section](https://github.com/olegantonyan/super_awesome_print/blob/5c97c804707a08470f54fbf7c6bfc25ce81121fd/README.md#contributing) you forgot to change the `[USERNAME]` to an actual username:

> Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/super_awesome_print. This ...

**Comment by olegantonyan** [comment]
Thanks!
