### ISSUE TITLE
Using sap in delegators

### ISSUE THREAD

**Issue by EvgeniyRRU** [olegantonyan/super_awesome_print#6]
Sometimes it very helpful to use delegator pattern. But sap gem does not work here.

``` ruby
class SuperNameSpace::SuperHandyClass < Delegator

  def initialize(attrs = {})
    # something here
  end

  def cat_meow
    cat = Pets.new(type: :cat)
    sap cat # cuased undefined method `sap' for module `Kernel'
    cat.meow
  end
end
```

Is it possible to fix it? May be I should to use monkey-patching for **Delegator**  class?

**Comment by olegantonyan** [comment]
Interesting. I have to investigate this

**Comment by olegantonyan** [comment]
Apparently, `Delegator` won't work with any methods defined outside module/class. 

``` ruby
def some_func
  puts '12'
end

class Klass < Delegator
  def initialize(obj)
    @obj = obj
  end

  def __getobj__
    @obj
  end

  def func
    some_func #=> boom!
  end
end

Klass.new(0).func
```

When there is no such method on object delegator delegates to it will try to call this method on `Kernel` explicitly (https://github.com/ruby/ruby/blob/trunk/lib/delegate.rb#L85). But for some reasons `Kernel.respond_to?(:sap, true)` is true and `Kernel.instance_method(:sap)` blows up. Probably bug in Ruby.

The solution is to define global method on `Kernel` module. But I'd like to investigate this strange behavior more (http://stackoverflow.com/questions/35637000/ruby-delegator-call-method-defined-outside-class-module-nameerror)

**Comment by olegantonyan** [comment]
https://bugs.ruby-lang.org/issues/12113
