### ISSUE TITLE
Support for old Ruby versions

### ISSUE THREAD

**Issue by EvgeniyRRU** [olegantonyan/super_awesome_print#9]
Hello, mr. Oleg. Is it possible to implement working this gem in old ruby versions (aka 1.8)? Is is possible to implement hash-rocket syntax for old rubies? See screenshot.
![console output](http://i.imgur.com/x4Iau6Q.png)

**Comment by olegantonyan** [comment]
Hi
This should be possible as long as awesome_print supports 1.8 (up to 1.2 version as they said https://github.com/awesome-print/awesome_print)
I'll check this on weekends

**Comment by EvgeniyRRU** [comment]
@olegantonyan, oh, no, it impossible, because you use new Ruby js-like hash syntax, not hash-rocket. I am about [this line](https://github.com/olegantonyan/super_awesome_print/blob/master/lib/super_awesome_print.rb#L8), for expample. These syntax begun support for Ruby 1.9.

**Comment by EvgeniyRRU** [comment]
If you beware hash-rocket, may be I should to use nested Structs and convert it to hash? But I think, it's a crappy. May be we should to divide main module to two versions? First for modern Rubies (with js-like hash sytax), and second for legacy Ruby versions (with hash-rocket hash syntax). I don't know exactly...

**Comment by olegantonyan** [comment]
Yeah, I get it. I'll do something, don't worry :)

**Comment by olegantonyan** [comment]
fixed in 0.2.3

**Comment by EvgeniyRRU** [comment]
@olegantonyan, thank you, all works fine!
